export * from '@ws/interfaces/crud-grid.interface';
export * from '@ws/interfaces/form.interface';
export * from '@ws/interfaces/http.interface';
export * from '@ws/interfaces/list.interface';
export * from '@ws/interfaces/notification.interface';
export * from '@ws/interfaces/provider.interface';
export * from '@ws/interfaces/result-grid.interface';
export * from '@ws/interfaces/result.interface';
export * from '@ws/interfaces/socket-io.config';
